### ISSUE TITLE
I'd love more information on this.

### ISSUE THREAD

**Issue by Leopere** [larserdmann/veracrypt-in-docker#1]
What are all of the environment variables you use and what's the workflow of how this container works?  I want to consider this container for use in a secure storage environment.

**Comment by larserdmann** [comment]
Hello, 
thanks for your questions. I have revised the description of my project and hopefully I can clarify one of your questions.

The variables in the shell scripts help me to keep track of the different directories and files. On the other hand it is easier to change certain file paths at a global location. Therefore I used the environment variables.

If you have any further questions, feel free to ask me.

With kind regards
